app:
  datasource:
    writer:
      jdbcUrl: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: password
      driver-class-name: org.postgresql.Driver
    reader:
      jdbcUrl: jdbc:postgresql://localhost:5433/postgres
      username: replicator
      password: replicator_password
      driver-class-name: org.postgresql.Driver

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
