services:
  exampledb:
      image: postgres
      container_name: exampledb
      environment:
        POSTGRES_DB: exampledb
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      restart: unless-stopped
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data

volumes:
  postgres_data:
  cache:
    driver: local