spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/exampledb
    username: admin
    password: admin
    hikari:
      pool-name: app-hikari-pool
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1200000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  logging:
    level:
      com.zaxxer.hikari: DEBUG